spring.application.name=eventhub

# MySQL Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/eventhub?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true

spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate settings for automatic schema creation
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Use MySQL dialect
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# custom path per swagger
# springdoc.swagger-ui.path=/swagger
#springdoc.swagger-ui.enabled=false
# la consegna chiede questo specifico
# springdoc.swagger-ui.path=/swagger-ui.html

# custom path per API docs (così per il json, con .yaml per lo yaml)
springdoc.api-docs.path=/apidocs
#springdoc.api-docs.enabled=false

# impostazione di Jacskon per produrre i json: non mandare i valori nulli
spring.jackson.default-property-inclusion=non_null

# Show JPA/Hibernate logging messages
logging.level.org.hibernate.SQL=trace
logging.level.org.hibernate.orm.jdbc.bind=trace

# spring security impostazione per vedere solo i log
logging.level.org.springframework.security=debug

# impostazione per ridurre il logging e tenere solo i warn
logging.level.root=warn

# Spring Data REST properties: per le rest api
# spring.data.rest.base-path=/api

